# Generated by Django 5.2 on 2025-04-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='frecuencia_compra',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='descuento_aplicado',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='es_promocion',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='fue_comprado',
        ),
    ]
