from django.db.models.signals import post_migrate
from django.dispatch import receiver
from .models import Estado, MetodoPago, Sucursal, Marca, Etiqueta, Categoria
from django.contrib.auth import get_user_model

@receiver(post_migrate)
def crear_datos_basicos(sender, **kwargs):
    MetodoPago.objects.get_or_create(nombre='Efectivo')
    MetodoPago.objects.get_or_create(nombre='QR')
    MetodoPago.objects.get_or_create(nombre='Transferencia')

    Sucursal.objects.get_or_create(nombre='Sucursal Central',ciudad='Santa cruz de la sierra', latitud=-17.78, longitud=-63.18)
    Sucursal.objects.get_or_create(nombre='Sucursal Norte',ciudad='Montero', latitud=-17.76, longitud=-63.15)

    Marca.objects.get_or_create(nombre='Sony')
    Marca.objects.get_or_create(nombre='Samsung')
    Marca.objects.get_or_create(nombre='LG')
    Marca.objects.get_or_create(nombre='Apple')
    Marca.objects.get_or_create(nombre='Dell')
    Marca.objects.get_or_create(nombre='HP (Hewlett-Packard)')
    Marca.objects.get_or_create(nombre='Lenovo')
    Marca.objects.get_or_create(nombre='Microsoft')
    Marca.objects.get_or_create(nombre='Bose')
    Marca.objects.get_or_create(nombre='Panasonic')
    Marca.objects.get_or_create(nombre='Canon')
    Marca.objects.get_or_create(nombre='Nikon')
    Marca.objects.get_or_create(nombre='JBL')
    Marca.objects.get_or_create(nombre='Razer')
    Marca.objects.get_or_create(nombre='Asus')
    Marca.objects.get_or_create(nombre='Acer')
    Marca.objects.get_or_create(nombre='Intel')
    Marca.objects.get_or_create(nombre='AMD')
    Marca.objects.get_or_create(nombre='Seagate')
    Marca.objects.get_or_create(nombre='Western Digital')
    Marca.objects.get_or_create(nombre='Logitech')
    Marca.objects.get_or_create(nombre='GoPro')
    Marca.objects.get_or_create(nombre='Philips')
    Marca.objects.get_or_create(nombre='Xiaomi')
    Marca.objects.get_or_create(nombre='Huawei')
    Marca.objects.get_or_create(nombre='Toshiba')
    Marca.objects.get_or_create(nombre='Corsair')
    Marca.objects.get_or_create(nombre='Epson')
    Marca.objects.get_or_create(nombre='Anker')
    Marca.objects.get_or_create(nombre='TechNova')
    Marca.objects.get_or_create(nombre='Voltix')
    Marca.objects.get_or_create(nombre='ElectronixPro')
    Marca.objects.get_or_create(nombre='HyperGadget')
    Marca.objects.get_or_create(nombre='SmartWave')
    Marca.objects.get_or_create(nombre='PixelCore')
    Marca.objects.get_or_create(nombre='QuantumX')
    Marca.objects.get_or_create(nombre='ZenithTech')
    Marca.objects.get_or_create(nombre='FutureWave')
    Marca.objects.get_or_create(nombre='ByteCraft')
    Marca.objects.get_or_create(nombre='Nexonix')
    Marca.objects.get_or_create(nombre='UltraGizmo')
    Marca.objects.get_or_create(nombre='MaxiTech')
    Marca.objects.get_or_create(nombre='EvoGear')
    Marca.objects.get_or_create(nombre='PrimeX')
    Marca.objects.get_or_create(nombre='NexGen Electronics')
    Marca.objects.get_or_create(nombre='InfinityTech')
    Marca.objects.get_or_create(nombre='VortexWave')
    Marca.objects.get_or_create(nombre='OmniTech')
    Marca.objects.get_or_create(nombre='GigaPulse')

    Etiqueta.objects.get_or_create(nombre='Pantalla táctil')
    Etiqueta.objects.get_or_create(nombre='Carga rápida')
    Etiqueta.objects.get_or_create(nombre='Bluetooth')
    Etiqueta.objects.get_or_create(nombre='Impermeable')
    Etiqueta.objects.get_or_create(nombre='Alta resolución')
    Etiqueta.objects.get_or_create(nombre='Sin cables')
    Etiqueta.objects.get_or_create(nombre='Pantalla 4K')
    Etiqueta.objects.get_or_create(nombre='Batería de larga duración')
    Etiqueta.objects.get_or_create(nombre='Antirreflejo')
    Etiqueta.objects.get_or_create(nombre='Compatibilidad con Android')
    Etiqueta.objects.get_or_create(nombre='Compatibilidad con iOS')
    Etiqueta.objects.get_or_create(nombre='Conexión USB-C')
    Etiqueta.objects.get_or_create(nombre='Diseño compacto')
    Etiqueta.objects.get_or_create(nombre='Control remoto')
    Etiqueta.objects.get_or_create(nombre='VR (Realidad Virtual)')
    Etiqueta.objects.get_or_create(nombre='Alta fidelidad de sonido')
    Etiqueta.objects.get_or_create(nombre='A prueba de golpes')
    Etiqueta.objects.get_or_create(nombre='Portátil')
    Etiqueta.objects.get_or_create(nombre='HDMI')
    Etiqueta.objects.get_or_create(nombre='Alta definición')
    Etiqueta.objects.get_or_create(nombre='Wi-Fi 6')
    Etiqueta.objects.get_or_create(nombre='Procesador rápido')
    Etiqueta.objects.get_or_create(nombre='Reducción de ruido')
    Etiqueta.objects.get_or_create(nombre='Resistente al agua')
    Etiqueta.objects.get_or_create(nombre='Pantalla OLED')
    Etiqueta.objects.get_or_create(nombre='Streaming')
    Etiqueta.objects.get_or_create(nombre='Cámara 4K')
    Etiqueta.objects.get_or_create(nombre='Sensor de huella')
    Etiqueta.objects.get_or_create(nombre='Pantalla curva')

    Categoria.objects.get_or_create(nombre='Smartphones')
    Categoria.objects.get_or_create(nombre='Laptops')
    Categoria.objects.get_or_create(nombre='Tabletas')
    Categoria.objects.get_or_create(nombre='Accesorios para teléfonos')
    Categoria.objects.get_or_create(nombre='Auriculares y audífonos')
    Categoria.objects.get_or_create(nombre='Cámaras y videocámaras')
    Categoria.objects.get_or_create(nombre='Televisores')
    Categoria.objects.get_or_create(nombre='Electrodomésticos')
    Categoria.objects.get_or_create(nombre='Computadoras de escritorio')
    Categoria.objects.get_or_create(nombre='Videojuegos y consolas')
    Categoria.objects.get_or_create(nombre='Dispositivos de streaming')
    Categoria.objects.get_or_create(nombre='Baterías externas')
    Categoria.objects.get_or_create(nombre='Relojes inteligentes')
    Categoria.objects.get_or_create(nombre='Cargadores y cables')
    Categoria.objects.get_or_create(nombre='Sistemas de sonido')


    Estado.objects.get_or_create(nombre='Procesando', defaults={'descripcion': 'Orden en proceso de preparación'})
    Estado.objects.get_or_create(nombre='Enviado', defaults={'descripcion': 'Orden enviada al cliente'})
    Estado.objects.get_or_create(nombre='Entregado', defaults={'descripcion': 'Orden entregada exitosamente'})
    Estado.objects.get_or_create(nombre='Cancelado', defaults={'descripcion': 'Orden cancelada'})

    # ✅ Crear superusuario automáticamente
    User = get_user_model()
    if not User.objects.filter(username='reymar').exists():
        User.objects.create_superuser(username='reymar', email='reymar@example.com', password='reymar123')
        print("✅ Superusuario 'reymar' creado automáticamente.")
   
    print("✅ Datos básicos iniciales cargados.")